# ---------------------- #
#      Site Configs      #
# ---------------------- #

title: My Blog
url: http://my-blog.com
permalink: /blog/:title.html
paginate: 10
paginate_path: /page/:num


# ---------------------- #
#         Jekyll         #
# ---------------------- #

safe: true
markdown: redcarpet
exclude: ['Gemfile', 'Gemfile.lock']
# destination: _site
# server_port: 4000


# ---------------------- #
#      Compile Sass      #
# ---------------------- #

# run `compass help compile` in terminal to find more available options
compile:
  no_line_comments: true
  sass_dir: _sass
  # css_dir: stylesheets
  # output_style: compressed


# ---------------------- #
#       Deployment       #
# ---------------------- #

deploy:
  repository:
  branch:


# ---------------------- #
#    Social Networks     #
# ---------------------- #

# weibo:
#   username:
#   uid:
#   appkey:

# duoshuo:

# google_analytics:
